// Generates src/styles/tokens.css from design/tokens.mjs.
import { writeFileSync } from 'node:fs';
import { semantic, space, radius, duration, easing, fonts, type, elevation, resolve } from './tokens.mjs';

const lines = [];
const out = (s = '') => lines.push(s);
const px = (n) => `${n}px`;
// Linear interpolation between 375px and 1440px viewports, clamped at both ends.
const fluid = (min, max) => {
  if (min === max) return px(max);
  const slope = (max - min) / (1440 - 375);
  const intercept = min - slope * 375;
  return `clamp(${px(min)}, ${(intercept / 16).toFixed(4)}rem + ${(slope * 100).toFixed(4)}vw, ${px(max)})`;
};

out('/* Generated by design/build-tokens.mjs from design/tokens.mjs. Do not edit by hand. */');
out('/* Names mirror the Figma variables: `color/bg` <-> `--color-bg`. */');
out();
out(':root {');
out('  color-scheme: light;');
for (const [name, [light]] of Object.entries(semantic)) out(`  --color-${name}: ${resolve(light)};`);
out();
for (const [k, v] of Object.entries(space)) out(`  --space-${k}: ${px(v)};`);
out();
for (const [k, v] of Object.entries(radius)) out(`  --radius-${k}: ${px(v)};`);
out();
for (const [k, v] of Object.entries(duration)) out(`  --duration-${k}: ${Math.round(v * 1000)}ms;`);
for (const [k, v] of Object.entries(easing)) out(`  --ease-${k}: cubic-bezier(${v.join(', ')});`);
out();
for (const [k, v] of Object.entries(fonts)) out(`  --font-${k}: ${v.css};`);
for (const [k, t] of Object.entries(type)) {
  out(`  --type-${k}-size: ${fluid(t.min, t.size)};`);
  out(`  --type-${k}-weight: ${t.weight};`);
  out(`  --type-${k}-leading: ${t.lh};`);
  out(`  --type-${k}-tracking: ${(t.ls / 100).toFixed(3)}em;`);
}
out();
for (const [k, v] of Object.entries(elevation)) out(`  --elevation-${k}: ${v};`);
out('}');
out();
const dark = [];
for (const [name, [, d]] of Object.entries(semantic)) dark.push(`  --color-${name}: ${resolve(d)};`);
const darkShadow = [
  '  --elevation-1: 0 1px 2px rgba(0, 0, 0, 0.5);',
  '  --elevation-2: 0 2px 4px rgba(0, 0, 0, 0.4), 0 10px 28px -10px rgba(0, 0, 0, 0.7);',
  '  --elevation-3: 0 4px 10px rgba(0, 0, 0, 0.45), 0 28px 64px -24px rgba(0, 0, 0, 0.85);',
];
out(':root[data-theme=\'dark\'] {');
out('  color-scheme: dark;');
dark.forEach((l) => out(l));
darkShadow.forEach((l) => out(l));
out('}');
out();
out('/* Type utilities: one class per ramp step. */');
for (const k of Object.keys(type)) {
  out(`.type-${k} {`);
  out(`  font-family: var(--font-${type[k].font});`);
  out(`  font-size: var(--type-${k}-size);`);
  out(`  font-weight: var(--type-${k}-weight);`);
  out(`  line-height: var(--type-${k}-leading);`);
  out(`  letter-spacing: var(--type-${k}-tracking);`);
  out('}');
}
writeFileSync(new URL('../src/styles/tokens.css', import.meta.url), lines.join('\n') + '\n');
console.log(`wrote src/styles/tokens.css (${lines.length} lines)`);
